
---

- name: install confluence
 # hosts: all
  hosts: instances
  become: yes

  tasks:
  - name: Preparing for installation
    shell: sudo apt update
    shell: sudo apt install -y default-jre
    shell: sudo echo "export JAVA_HOME=/usr" >> .bashrc
    shell: sudo echo "export PATH=$JAVA_HOME/bin:$PATH" >> .bashrc
    shell: sudo mkdir /home/ubuntu/confluence

  - name: create home folder and giving rights
    shell: sudo chmod -R confluence /home/ubuntu/confluence
    shell: sudo chmod -R u=rwx,go-rwx /home/ubuntu/confluence

    shell: sudo mkdir /home/ubuntu/confluence-home
    shell: sudo chmod -R confluence /home/ubuntu/confluence-home
    shell: sudo chmod -R u=rwx,go-rwx /home/ubuntu/confluence-home


  - name: Creating user for Confluence
   
    shell: sudo /usr/sbin/useradd --create-home --comment "Account for running Confluence" --shell /bin/bash confluence  

  - name: Installing DB (PostgreSQL)
    shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    shell: sudo apt-get update
    shell: sudo apt-get -y install postgresql

   
  - name: Download
    
    shell: wget https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.12.2.tar.gz /home/ubuntu/confluence

  - name: Unzip   
    shell: sudo tar -xzf /home/ubuntu/atlassian-confluence-7.12.2.tar.gz -C /home/ubuntu/confluence
    shell: sudo tar -xf /home/ubuntu/confluence/atlassian-confluence-7.12.2.tar

 # - name: editing
   # shell: sudo echo "confluence.home=/var/confluence-home" >> /home/ubuntu/confluence/confluence.init.properties   
 # - name: 
    
...
